### ISSUE TITLE
UWP crash in sideloaded release build

### ISSUE THREAD

**Issue by cleardemon** [aritchie/userdialogs#133]
Under Windows 10 (desktop, UWP), my app is crashing when it is built for release and sideloaded on a test computer. Recovering the crash dump seems to suggest there is an issue with UserDialogs.

The exception message is "XAML parsing failed." and the stack trace is as follows:

```
    at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
    at Acr.UserDialogs.ProgressContentDialog.InitializeComponent()
    at Acr.UserDialogs.ProgressDialog..ctor()
    at Acr.UserDialogs.UserDialogsImpl.CreateDialogInstance()
    at Acr.UserDialogs.AbstractUserDialogs.Progress(ProgressDialogConfig config)
    at Acr.UserDialogs.AbstractUserDialogs.Loading(String title, Action onCancel, String cancelText, Boolean show, Nullable`1 maskType)
    at Acr.UserDialogs.AbstractUserDialogs.ShowLoading(String title, Nullable`1 maskType)
    at Syncode.Swapped.Platform.Forms.Services.OverlayServiceAcrUserDialogs.ShowLoadingAsync(String message) in C:\Users\[redacted]\Platform\Forms\Services\OverlayServiceAcrUserDialogs.cs:line 18
    at Syncode.Swapped.Platform.Forms.MainPage.<HandleLoadingPastes>d__16.MoveNext()
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
    at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
```

Is there anything I need to check to make sure that the XAML is parsed? Are the XAML files supposed to be part of the distribution or are they supposed to be in the DLL?

Running from Visual Studio is fine, but it only seems to be a problem when the app is sideloaded (as per [these instructions](https://msdn.microsoft.com/en-us/library/hh454036.aspx#Anchor_3)).

**Comment by aritchie** [comment]
Please follow #112
