### ISSUE TITLE
IllegalArgumentException after scanning with ZXing Mobile Scanner

### ISSUE THREAD

**Issue by Vandersteen** [aritchie/userdialogs#135]
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[] iOS
[x] Android
[] WP81
[] WP8
[] UWP
[] PCL

2) Please state the issue to the best of your ability below

Using ZXing Mobile Scanner scanview and then showing and hiding a Loading (.ShowLoading("loading") & .HideLoading()) results in a IllegalArgumentsException:

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

```
Java.Lang.IllegalArgumentExceptionView=com.android.internal.policy.PhoneWindow$DecorView{3f90243 G.E...... R.....ID 0,0-282,198} not attached to window manager
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9cd30cf0 + 0x00024> in <filename unknown>:0 
  at Android.Runtime.JNIEnv.CallVoidMethod (IntPtr jobject, IntPtr jmethod) <0x9c3c0f10 + 0x000a7> in <filename unknown>:0 
  at Android.App.Dialog.Dismiss () <0x9a614008 + 0x000ab> in <filename unknown>:0 
  at AndroidHUD.AndHUD+<DismissCurrent>c__AnonStorey4.<>m__0 () <0x9a613dc8 + 0x0003b> in <filename unknown>:0 
  at AndroidHUD.AndHUD+<DismissCurrent>c__AnonStorey4.<>m__1 (System.Object state) <0x9a613d90 + 0x00027> in <filename unknown>:0 
  at Android.App.SyncContext.Send (System.Threading.SendOrPostCallback d, System.Object state) <0x99cc9f78 + 0x0007b> in <filename unknown>:0 
  at AndroidHUD.AndHUD.DismissCurrent (Android.Content.Context context) <0x99cc98d0 + 0x0019b> in <filename unknown>:0 
  at AndroidHUD.AndHUD.Dismiss (Android.Content.Context context) <0x9a613d60 + 0x0001b> in <filename unknown>:0 
  at Acr.UserDialogs.ProgressDialog.<Hide>b__26_0 () <0x9a613d00 + 0x00027> in <filename unknown>:0 
  at Acr.Support.Android.Extensions.RequestMainThread (System.Action action) <0x99cc8a50 + 0x0005f> in <filename unknown>:0 
  at Acr.UserDialogs.ProgressDialog.Hide () <0x9a613c40 + 0x00077> in <filename unknown>:0 
  at Acr.UserDialogs.ProgressDialog.Dispose () <0x9a613c00 + 0x0001f> in <filename unknown>:0 
  at Acr.UserDialogs.AbstractUserDialogs.HideLoading () <0x9a613b58 + 0x0003f> in <filename unknown>:0 
  at B2B.DashboardPage.undoBusy () <0x9a613a88 + 0x0005b> in <filename unknown>:0 
  at B2B.DashboardPage+<GetActions>c__async6.MoveNext () <0x99930c20 + 0x00777> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x9cd30cf0 + 0x00024> in <filename unknown>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) <0xb0163428 + 0x0003f> in <filename unknown>:0 
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () <0x9a613980 + 0x00027> in <filename unknown>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () <0x9b4e46e8 + 0x0003f> in <filename unknown>:0 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) <0x9b4e4640 + 0x0003f> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:86334b81-7da6-4cef-be03-bba56daa8999 (intptr,intptr)
  --- End of managed exception stack trace ---
java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{3f90243 G.E...... R.....ID 0,0-282,198} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:362)
	at android.app.Dialog.dismiss(Dialog.java:345)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```

**Comment by aritchie** [comment]
It looks like you are dismissing the dialog on the wrong activity.  Please submit a code sample with the pre/post code of the progress dialog

**Comment by Vandersteen** [comment]
It goes along the lines of:

```
var scanner = new ZXing.Mobile.MobileBarcodeScanner();

var result = await scanner.Scan();
if (result != null) {

 UserDialogs.Instance.ShowLoading ("Just one moment", MaskType.Black);

 //Perform some checks & an api request

 UserDialogs.Instance.HideLoading();

}
```

**Comment by aritchie** [comment]
Are you using Xamarin Forms?  In your "perform stuff", are you doing a navigate of some sort?  This error usually occurs when you navigate away from a screen and then try to close the loading dialog.

**Comment by Vandersteen** [comment]
I am using Xamarin Forms.

The loading is closed after the request is finished. Then a new page is pushed as a modal. So the swapping of the page should come after the hiding of the loading.

Visualy it looks like the loading is not fired untill the very end and then crashes.

**Comment by Vandersteen** [comment]
I resolved the issue.

The result came back before the scan modal was closed by ZXing. So the 'loading' was initiated in the 'wrong activity'.

Using the ZXing for Forms:

Initiating:
```
_ScanPage = new ZXingScannerPage ();
_ScanPage.OnScanResult += _ScanPage_OnScanResult;
await Navigation.PushModalAsync (_ScanPage);
```

```
void _ScanPage_OnScanResult (ZXing.Result result)
{
	_ScanPage.IsScanning = false;
	_ScanPage.OnScanResult -= _ScanPage_OnScanResult;
	_ScanPage = null;

	// Pop the page and show the result
	Device.BeginInvokeOnMainThread (async () => {
		await Navigation.PopModalAsync (false);
		
                //Now show loading
                // Do some processing
                // Hide loading
	});
}
```

And it works.

Thank you for your time !
