### ISSUE TITLE
[Android] Error after app dismiss and reopen with notification from service

### ISSUE THREAD

**Issue by SergioZgz** [aritchie/userdialogs#137]
HI,

(I'm pretty sure that the problem is mine and not from your component, but I cannot fix it in any way, I you test it, and works, but you havent time to help me just told me and I close the bug, no problem :) )

I have an app with service which has a notification, everything works perfect until I close the app, then I touch the notification to reopen the app the app works but when I try to show a ActionSheet I get this error:

"Unable to add window -- token android.os.BinderProxy@30881a8 is not valid; is your activity running?"

StackTrace:
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Android.Runtime.JNIEnv.CallVoidMethod (IntPtr jobject, IntPtr jmethod) [0x00062] in /Users/builder/data/lanes/2692/e98e9627/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:554 
  at Android.App.Dialog.Show () [0x00043] in /Users/builder/data/lanes/2692/e98e9627/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.App.Dialog.cs:3022 
  at Acr.UserDialogs.Extensions.ShowExt (Android.App.Builder builder) [0x00012] in C:\dev\userdialogs\src\Acr.UserDialogs.Android\Extensions.cs:40 
  at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass6_0.<ActionSheet>b__6 () [0x00000] in C:\dev\userdialogs\src\Acr.UserDialogs.Android\UserDialogsImpl.cs:84 
  at Acr.Support.Android.Extensions.RequestMainThread (System.Action action) [0x00019] in <filename unknown>:0 
  at Acr.UserDialogs.UserDialogsImpl.ActionSheet (Acr.UserDialogs.ActionSheetConfig config) [0x0016d] in C:\dev\userdialogs\src\Acr.UserDialogs.Android\UserDialogsImpl.cs:84 
  at XXXXXXX.Core.ViewModels.XXXXXXXXXViewModel.ContextMenu (XXXXX.Core.Entities.XXXXXX XXXXXXXX) [0x00097] in C:\Users\X\X\X.Core\ViewModels\xxxxxxxViewModel.cs:402 
  --- End of managed exception stack trace ---
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@30881a8 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:571)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:319)
	at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
	at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:29)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21155)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by SergioZgz** [comment]
Arf ... last test make this work... 

I was doing some test this weekend and by mistake I installed from nuget an old version of userdialog... with that version I have to use this to initialize UserDialogs.Init(() => this);

Changing that for this: UserDialogs.Init(this); solve the problem... I need sleep more and code less hahaha

**Comment by rrvind** [comment]
thanks for commenting you solution. i had the same problem and done the exact same thing...
