### ISSUE TITLE
XamlParseException Win Phone 8.1

### ISSUE THREAD

**Issue by raghurana** [aritchie/userdialogs#148]
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[] iOS
[] Android
[x] WP81
[] WP8
[] UWP
[] PCL

2) Please state the issue to the best of your ability below

Create a brand new Windows Phone 8.1 app, get the package from Nuget 4.3.4. Call   UserDialogs.Instance.Loading("Test") in the OnNavigatedTo(NavigationEventArgs e). This throws a XamlParseException.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

Stack Trace:

   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Acr.UserDialogs.ProgressContentDialog.InitializeComponent()
   at Acr.UserDialogs.ProgressDialog..ctor()
   at Acr.UserDialogs.UserDialogsImpl.CreateDialogInstance()
   at Acr.UserDialogs.AbstractUserDialogs.Progress(ProgressDialogConfig config)
   at Acr.UserDialogs.AbstractUserDialogs.Loading(String title, Action onCancel, String cancelText, Boolean show, Nullable`1 maskType)
   at TestWindwsApp.MainPage.OnNavigatedTo(NavigationEventArgs e)

**Comment by aritchie** [comment]
I'm no longer supporting wp8.  I'll take a pr for it, but that is about it
