### ISSUE TITLE
XAML Parsing Failed.

### ISSUE THREAD

**Issue by jzeferino** [aritchie/userdialogs#151]
#### 1) Issue in:
[x] WP81

#### 2) Explanation:
Hello, i have a Xamarin Froms project running with the version `(2.2.0.5-pre2)` and running the `Acr.UserDialogs (4.3.4)`.

In my WP81 project im using the forms version `(2.2.0.5-pre2) `and the `Acr.UserDialogs (4.3.4)`.
After my application launch when i click a button i show a loading and and `XAML Parsing Failed Exception` is thrown.

I tried to downgrade to `Acr.UserDialogs (4.3.3)` and `Acr.UserDialogs (4.3.2)` but get the same result.

#### 3) Full stack here:
   ```
at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Acr.UserDialogs.ProgressContentDialog.InitializeComponent()
   at Acr.UserDialogs.ProgressDialog..ctor()
   at Acr.UserDialogs.UserDialogsImpl.CreateDialogInstance()
   at Acr.UserDialogs.AbstractUserDialogs.Progress(ProgressDialogConfig config)
   at Acr.UserDialogs.AbstractUserDialogs.Loading(String title, Action onCancel, String cancelText, Boolean show, Nullable`1 maskType)
   at Acr.UserDialogs.AbstractUserDialogs.ShowLoading(String title, Nullable`1 maskType)
   at FullSharedCode.PhotoService.<LoadImageAsync>d__1.MoveNext()

```

**Comment by jzeferino** [comment]
@aritchie thank you for the reply. As a duplicate issue, can you please point me to a possible solution/workaround since I searched for similar issues and didn't find anything.

**Comment by aritchie** [comment]
I'm not supporting wp8 any longer as I've stated in other closed issues.  If I knew the answer to this problem, it would already be fixed and I won't invest any time on a dead platform.  PRs are welcome but use at your own risk

**Comment by jzeferino** [comment]
Ok thanks for the reply.
I will move now to universal apps.

**Comment by ThumbGen** [comment]
Please remove WP81 completely if it is not fully supported; this will save minutes/hours of frustration for the developers using the library and don't expecting it to crash in unexpected places.

**Comment by aritchie** [comment]
ThumbGreen - read the readme.md 
I state right there that it comes with no support.
