### ISSUE TITLE
Dialog failing on UWP Platform , if title wasn't supplied

### ISSUE THREAD

**Issue by sleonidy** [aritchie/userdialogs#179]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [] Android
 - [x] UWP
 - [] PCL

2) Please state the issue to the best of your ability below
ConfirmAsync failing with exception on UWP platform, when title wasn't supplied, while other platform doesn't have such issue and title default value can be null

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
Exception: {"Value cannot be null."}
Stacktrace:
   at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)
   at Windows.UI.Popups.MessageDialog..ctor(String content, String title)
   at Acr.UserDialogs.UserDialogsImpl.Confirm(ConfirmConfig config)
   at Acr.UserDialogs.AbstractUserDialogs.ConfirmAsync(ConfirmConfig config, Nullable`1 cancelToken)
   at Acr.UserDialogs.AbstractUserDialogs.ConfirmAsync(String message, String title, String okText, String cancelText, Nullable`1 cancelToken)

**Comment by aritchie** [comment]
fixed for 5.3
