### ISSUE TITLE
java.lang.IllegalStateException: Activity has been destroyed in MarshMallow 6.0

### ISSUE THREAD

**Issue by raphaelcr93** [aritchie/userdialogs#219]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

Every first time Im calling In MarshMallow (6.0) any Alert like:
var r = await UserDialogs.Instance.ConfirmAsync("a","a","a","a")

Im getting a java.lang.IllegalStateException: Activity has been destroyed

In the second try it works sometimes.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (JniObjectReference instance, JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in /Users/builder/data/lanes/3415/7db2aac3/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12083 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00068] in /Users/builder/data/lanes/3415/7db2aac3/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:31 
  at Android.App.DialogFragment.Show (Android.App.FragmentManager manager, System.String tag) [0x00046] in /Users/builder/data/lanes/3415/7db2aac3/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.App.DialogFragment.cs:426 
  at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass25_0`2[TFragment,TConfig].<ShowDialog>b__0 () [0x00000] in C:\dev\acr\userdialogs\src\Acr.UserDialogs.Android\UserDialogsImpl.cs:273 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3415/7db2aac3/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3415/7db2aac3/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:81 
  at (wrapper dynamic-method) System.Object:bc7e8130-76fe-4fa2-bf00-3a00f85c7fb3 (intptr,intptr)
  --- End of managed exception stack trace ---
java.lang.IllegalStateException: Activity has been destroyed
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1433)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
	at android.app.BackStackRecord.commit(BackStackRecord.java:663)
	at android.app.DialogFragment.show(DialogFragment.java:230)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.app.Activity.runOnUiThread(Activity.java:5511)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:30)
	at android.view.View.performClick(View.java:5198)
	at android.view.View$PerformClick.run(View.java:21147)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by aritchie** [comment]
How are you calling Init?

**Comment by raphaelcr93** [comment]
In my mainActivity I call:

UserDialogs.Init(this);

after global::Xamarin.Forms.Forms.Init (this, bundle);

**Comment by aritchie** [comment]
Try UserDialogs.Init(() => (Activity)Forms.Context);

If that doesn't work for you, you'll need to provide an end to end sample with the issue.

**Comment by raphaelcr93** [comment]
Thanks,

This did not work.
However you put me in the right track.
I use a facebook plugin to LogIn in my app.
This plugin seems like to change the context activity.
What I had to do, was to initialize the component again before using it.

Is there any risk to Init it out of the mainActivity?

**Comment by aritchie** [comment]
No.  You shouldn't need to do this though.  The UserDialogs.Init(Activity) (the original call you were making) installs a applifecycle manager that picks up the changing activity views.  Not sure why that is failing in the particular case you have listed.  If you can supply a test case for this, I can look into a potential fix.

**Comment by aritchie** [comment]
Please send a reproducible sample and I will reopen this
