### ISSUE TITLE
Displaying Confirm AcrUserDialog when app is in background, throws error

### ISSUE THREAD

**Issue by teau01** [aritchie/userdialogs#230]
Steps to reproduce:
1. App has timer, which should display ConfirmDialog 
2. When app is minimized (in background) , throws the error shown bellow, when is trying to display dialog.

Exception message:
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3236/ee215fc9/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00084] in /Users/builder/data/lanes/3236/ee215fc9/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1029 
  at Android.Support.V4.App.DialogFragment.Show (Android.Support.V4.App.FragmentManager manager, System.String tag) [0x000ab] in <filename unknown>:0 
  at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass26_0`2[TFragment,TConfig].<ShowDialog>b__0 () [0x00016] in C:\dev\acr\userdialogs\src\Acr.UserDialogs.Android\UserDialogsImpl.cs:287 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3236/ee215fc9/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3236/ee215fc9/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Java.Lang.IRunnable.cs:71 
  at (wrapper dynamic-method) System.Object:b9c9fa8e-8993-4f28-b827-c1594dac36ca (intptr,intptr)
  --- End of managed exception stack trace ---
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:617)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by aritchie** [comment]
How is this a problem with dialogs?  You can present them if they aren't in the foreground

**Comment by EmilAlipiev** [comment]
@teau01 have you ever found a good workaround or solution for this? I understand probably it is not good practice to show dialog when it is in the background. but background is not always switching apps. for example I am getting this crash when user locks his screen as well. I am having a timer activity where user performs some exercises and phone displays if you want to continue or not when the timer is displayed, I need to display this even when screen is locked. how to work around this problem please?

**Comment by EmilAlipiev** [comment]
Quick update this seems like a problem(or the way it is supposed to be according to its implemetation) AcrUserDialog in your dialog. I have just tried another Dialog from Freshmvvm and it doesnt cause this exception neither when screen is locked nor app is in the background.

**Comment by aritchie** [comment]
@EmilAlipiev There are ways you can check if your app is considered backgrounded.  Xamarin forms has some mechanisms as does 3rd party plugins.  You can also wrap your alert request in a try/catch as a worst case scenario.  The fact is though, this is not something I plan on ever implementing in user dialogs.

**Comment by MojoFilter** [comment]
Oh, dang. I wish I'd seen this before I started using the library. That's pretty huge.

**Comment by JTOne123** [comment]
Unfortunately, try/catch doesn't help and an app will crash anyway (version 6.5)

**Comment by aritchie** [comment]
@JTOne123 please do not post in closed issues, especially ones where I've stated what you can do (besides try/catch).  I've added a bunch of additional saves to 7.0.  You can use it or check foreground/background yourself.

**Comment by JTOne123** [comment]
Sorry for that!
Great news but the 7.0 is [Could not install package 'Acr.UserDialogs 7.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.]

**Comment by aritchie** [comment]
@JTOne123 please read the docs.  this library has been for .NET standard, not PCL.  It's been this way for a while.

**Comment by EmilAlipiev** [comment]
@aritchie  just a silly question. i am also using pcl profile still. I was able to install every new version until today even though it has been .net standard. What has changed with 7.0 version? is it because of 2.0?
