### ISSUE TITLE
Error Xamarin Forms (Android)

### ISSUE THREAD

**Issue by jbravobr** [aritchie/userdialogs#26]
--- End of managed exception stack trace ---
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	... 2 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
at Mais.ColetaDadosPage..ctor () [0x00020] in /Users/Rodrigo/Projects/Mais/Mais/Paginas/ColetaDadosPage.cs:14
at Mais.App..ctor () [0x00034] in /Users/Rodrigo/Projects/Mais/Mais/App.cs:26
at Mais.Droid.MainActivity.OnCreate (Android.OS.Bundle) [0x00032] in /Users/Rodrigo/Projects/Mais/Droid/MainActivity.cs:25
at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/1780/3518c4ce/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:2707
at (wrapper dynamic-method) object.18385e70-82f9-474a-a515-5db6fc07668d (intptr,intptr,intptr) <IL 0x00017, 0x0002b>

	at md51cfd4c7697c9573971f0f848647e699c.MainActivity.n_onCreate(Native Method)
	at md51cfd4c7697c9573971f0f848647e699c.MainActivity.onCreate(MainActivity.java:28)
	at android.app.Activity.performCreate(Activity.java:5231)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
	at android.app.ActivityThread.access$800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	... 5 more

**Comment by aritchie** [comment]
There isn't anything in the exception that says user dialogs.  Based on the exception, I'm guessing you are calling for a dialog before the view is available.  Use onappearing, not the page constructor

**Comment by jbravobr** [comment]
Thanks @aritchie  !!!!!!!!!!
