### ISSUE TITLE
Getting IllegalStateException from UserDialogsImpl.ShowDialog

### ISSUE THREAD

**Issue by mrbelk** [aritchie/userdialogs#262]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

Panasonic ToughPad FZ-X1 running Android 4.2.2.
Xamarin.Forms 2.3.2
Acr.UserDialogs v6.2.3
AppCompat 23.3.0.0

We have our app instrumented with HockeyApp and are seeing crash reports with IllegalStateExceptions occurring because UserDialogsImpl.ShowDialog is being called after onSaveInstanceState has been called. At this time, I can't identify where exactly in our code this is occurring since I believe that whatever call to UserDialogs that's causing this is being made in an anonymous method (either an event handler or MessageCenter subscription. Can you suggest the best way to identify when onSaveInstanceState is called so that we don't make the mistake of calling into your library?

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:617)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.app.Activity.runOnUiThread(Activity.java:4644)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5074)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
	at dalvik.system.NativeStart.main(Native Method)
Xamarin caused by: Java.Lang.IllegalStateException: Can not perform this action after onSaveInstanceState
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x71216130 + 0x00024> in <filename unknown>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (JniObjectReference instance, JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) <0x6d357f78 + 0x000d3> in <filename unknown>:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) <0x6d3750b0 + 0x000b3> in <filename unknown>:0 
  at Android.Support.V4.App.DialogFragment.Show (Android.Support.V4.App.FragmentManager manager, System.String tag) <0x786554d0 + 0x00233> in <filename unknown>:0 
  at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass27_0`2[TFragment,TConfig].<ShowDialog>b__0 () <0x786553b0 + 0x0006f> in <filename unknown>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () <0x6fe3f888 + 0x0003f> in <filename unknown>:0 
  at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) <0x6fe3f7e0 + 0x0003f> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:2cf4ff9c-785b-4248-805a-084e349b79aa (intptr,intptr)
```

**Comment by aritchie** [comment]
This isn't extremely helpful at all, so I'll take a very big guess.  It looks as though you're calling for one of the alert styled dialogs after an activity is pausing/destroying.

I can't help you much beyond that as this could be anything.

**Comment by mrbelk** [comment]
That's what I was afraid of. do you have any helpful hints on how to detect/avoid doing that? I've seen a couple examples of overriding onPause/onResume in the main activity to set a global boolean that the Xamarin.Forms app can check before doing anything like that, but that seems really kludgy to have to do that before calling every thing that might do something with the UI or window stack

**Comment by aritchie** [comment]
Hook your viewmodel up to the Xamarin forms onactivated/ondeactivated methods of a page and make sure you clean up your message center subscriptions in ondeactivated

**Comment by vandrham** [comment]
As a workaround, I use [Polly](https://www.nuget.org/packages/polly) to try a few times with given interval. In my case, the userdialog was called just before the android context was initialized and this will fix the timing issue:

```
// if UserDialogs.Instance.AlertAsync is called when the android activity is not ready yet,
// UserDialogs will cause a crash. This can be prevented by allowing it to wait a few milliseconds.
await Policy
    .Handle<Exception>()
    .WaitAndRetryAsync(retryCount: 10, sleepDurationProvider: retryAttempt => TimeSpan.FromMilliseconds(100))
    .ExecuteAsync(async () => await UserDialogs.Instance.AlertAsync("alert"));
```

**Comment by aritchie** [comment]
@vandrham while I appreciate the help for users, the idea is horrible in my opinion.  The activation/deactivation state is available on Android & iOS as well as Xamarin Forms.  You really should hook these events for proper usage here.  Keep in mind, user dialogs is a bit of a cheat in terms of view/viewmodel separation of concerns.

**Comment by winterdouglas** [comment]
Hello guys. 
I know this is an old thread but I recently faced the same problem on Android < 7 in some devices, only when in release.
I don't know exactly what was the problem but I know that disabling the LLVM solved my problem.

I hope it helps someone.

**Comment by mrbelk** [comment]
Hmm... I don't have LLVM enabled on this project in the "Release" build configuration. You're referring to the "sub selection" under the AOT compilation, right, or somewhere else?

**Comment by winterdouglas** [comment]
Yes, right, that sub-selection under AOT in Visual Studio. That was causing the problem for me.
