### ISSUE TITLE
Android: Java.Lang.NullPointerException is thrown on ShowLoading/ShowLogin/etc

### ISSUE THREAD

**Issue by Shaddix** [aritchie/userdialogs#3]
The simplest code from MainActivity:

    UserDialogs.Init (this);
    UserDialogs.Instance.ShowLoading ("asd");

throws Java.Lang.NullPointerException
The following one works correctly:

    AndHUD.Shared.Show(this, "Status Message");

I'm using 3.0.2 from Nuget.
Full exception text:
```
Java.Lang.NullPointerException: 
  at at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <IL 0x00011, 0x00047>
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue[]) [0x00084] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:896
  at Android.Runtime.JNIEnv.FinishCreateInstance (intptr,intptr,intptr,Android.Runtime.JValue[]) [0x0000b] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.cs:288
  at Android.App.Dialog..ctor (Android.Content.Context) [0x000ef] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Dialog.cs:85
  at at AndroidHUD.AndHUD/<SetupDialog>c__AnonStorey3.<>m__0 (object) <IL 0x0000d, 0x0005f>
  at Android.App.SyncContext.Send (System.Threading.SendOrPostCallback,object) [0x00025] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:26
  at at AndroidHUD.AndHUD.SetupDialog (Android.Content.Context,AndroidHUD.MaskType,System.Action,System.Func`4<Android.Content.Context, Android.App.Dialog, AndroidHUD.MaskType, Android.Views.View>) <IL 0x0003d, 0x001bb>
  at at AndroidHUD.AndHUD.showStatus (Android.Content.Context,bool,string,AndroidHUD.MaskType,System.Nullable`1<System.TimeSpan>,System.Action,bool,System.Action) <IL 0x000cd, 0x003db>
  at at AndroidHUD.AndHUD.Show (Android.Content.Context,string,int,AndroidHUD.MaskType,System.Nullable`1<System.TimeSpan>,System.Action,bool,System.Action) <IL 0x0002c, 0x0012f>
  at at Acr.UserDialogs.ProgressDialog/<>c__DisplayClass3.<Refresh>b__2 () <IL 0x00033, 0x0014f>
  at at Acr.UserDialogs.Utils.RequestMainThread (System.Action) <IL 0x0001f, 0x000b9>
  at at Acr.UserDialogs.ProgressDialog.Refresh () <IL 0x000b1, 0x0035f>
  at at Acr.UserDialogs.ProgressDialog.Show () <IL 0x00011, 0x00071>
  at at Acr.UserDialogs.AbstractUserDialogs.Progress (Acr.UserDialogs.ProgressDialogConfig) <IL 0x00042, 0x00178>
  at at Acr.UserDialogs.AbstractUserDialogs.Loading (string,System.Action,string,bool) <IL 0x0002c, 0x000c4>
  at at Acr.UserDialogs.AbstractUserDialogs.ShowLoading (string) <IL 0x0000e, 0x0005c>
  at WeDo.Droid.MainActivity.OnCreate (Android.OS.Bundle) [0x00034] in d:\WeDo\git\src\WeDo.Client\WeDo.Android\MainActivity.cs:36
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (intptr,intptr,intptr) [0x00011] in /Users/builder/data/lanes/monodroid-mlion-monodroid-4.21-series/49a04b96/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:2380
  at at (wrapper dynamic-method) object.e410249f-5413-47a1-a74c-a89decd6daf3 (intptr,intptr,intptr) <IL 0x00017, 0x0001f>
  at --- End of managed exception stack trace ---
  at java.lang.NullPointerException
  at at android.app.Dialog.<init>(Dialog.java:154)
  at at android.app.Dialog.<init>(Dialog.java:131)
  at at wedo.droid.MainActivity.n_onCreate(Native Method)
  at at wedo.droid.MainActivity.onCreate(MainActivity.java:28)
  at at android.app.Activity.performCreate(Activity.java:5133)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
  at at android.app.ActivityThread.access$600(ActivityThread.java:141)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
  at at android.os.Handler.dispatchMessage(Handler.java:99)
  at at android.os.Looper.loop(Looper.java:137)
  at at android.app.ActivityThread.main(ActivityThread.java:5103)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:525)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
  at at dalvik.system.NativeStart.main(Native Method)
```

**Comment by aritchie** [comment]
What is your API target?  I tried the code below which should match your exception.  It works for me.  Let me know.

	[Activity(Label = "Samples", Icon = "@drawable/icon", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
	public class TestActivity : Activity {
		protected override void OnCreate(Bundle bundle) {
			base.OnCreate(bundle);
			UserDialogs.Init(this);
			UserDialogs.Instance.ShowLoading("Test");
		}
	}

**Comment by Shaddix** [comment]
That was dumb of me, sorry :(
The problem is that I basically was doing this: ``UserDialogs.Init((Activity)null)``
It wasn't that clear for me, because that ``null`` value went through a rather complex logic first.

And even after i simplified it to ``UserDialogs.Init (this);`` from ``MainActivity`` it was a second call to .Init, and first one was still done with ``null`` as Activity.

I could only suggest to throw an exception, if ``UserDialogs.Init`` is initialized with ``null``, but that's completely up to you, sorry for wasting your time investigating this.

**Comment by aritchie** [comment]
No worries & I think you're right about the exception.  Thanks for letting me know.
