### ISSUE TITLE
NullReferenceException in Prompt after pressing "Enter" key on keyboard

### ISSUE THREAD

**Issue by mrbelk** [aritchie/userdialogs#302]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
4.2.2

## Version of ACR UserDialogs Library
6.3.2

## Expected Behaviour
Tapping the "enter" button on the soft keyboard should dismiss the prompt with an "OK" result

## Actual Behavior
a NullReferenceException is thrown on line 79 of the PromptDialogFragment.cs file where it looks for the text entry UI element.

```
Package: com.bizspeed.bulkDelivery
Version Code: 163411143
Version Name: 2016.12.6.1143
Android: 4.2.2
Android Build: tcd_tough-10-300-01-014-017
Manufacturer: PANASONIC
Model: FZ-X1
Thread: main-1
CrashReporter Key: 002AF90B-76FD-82DF-3C52-122B1D8D351897977403
Start Date: Tue Dec 06 16:34:11 EST 2016
Date: Tue Dec 06 19:40:20 EST 2016
Format: Xamarin

Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at Acr.UserDialogs.Fragments.PromptAppCompatDialogFragment.SetAction (Boolean ok) <0x78b2c6e0 + 0x00020> in <filename unknown>:0 
  at Acr.UserDialogs.Fragments.PromptAppCompatDialogFragment.OnKeyPress (System.Object sender, Android.Content.DialogKeyEventArgs args) <0x78b2ad90 + 0x0009b> in <filename unknown>:0 
  at Android.Content.IDialogInterfaceOnKeyListenerImplementor.OnKey (IDialogInterface dialog, Keycode keyCode, Android.Views.KeyEvent e) <0x7947c288 + 0x0006b> in <filename unknown>:0 
  at Android.Content.IDialogInterfaceOnKeyListenerInvoker.n_OnKey_Landroid_content_DialogInterface_ILandroid_view_KeyEvent_ (IntPtr jnienv, IntPtr native__this, IntPtr native_dialog, Int32 native_keyCode, IntPtr native_e) <0x7947c0c8 + 0x00093> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:b4652b5b-674d-4aa6-bddd-214bdffb0548 (intptr,intptr,intptr,int,intptr)
	at mono.android.content.DialogInterface_OnKeyListenerImplementor.n_onKey(Native Method)
	at mono.android.content.DialogInterface_OnKeyListenerImplementor.onKey(DialogInterface_OnKeyListenerImplementor.java:30)
	at android.app.Dialog.dispatchKeyEvent(Dialog.java:703)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1881)
	at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl.deliverKeyEvent(ViewRootImpl.java:3668)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3203)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4339)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4318)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3018)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5074)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
	at dalvik.system.NativeStart.main(Native Method)
```

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by mrbelk** [comment]
Thanks for looking at this. Any idea when this will be up on nuget?
