### ISSUE TITLE
Android - Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

### ISSUE THREAD

**Issue by dot-ly** [aritchie/userdialogs#328]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
 Android 6.0

## Version of ACR UserDialogs Library

6.3.7

## Expected Behaviour
Display a Toast with message

## Actual Behavior
Trying to show a basic toast after a button click on android
```
IUserDialogs _dialogs = Mvx.Resolve<IUserDialogs>();
ToastConfig config = new ToastConfig("test");
config.SetDuration(5000);
_dialogs.Toast(config);
```

```
Java.Lang.RuntimeException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a1f6de3b214c442f9c56859bdd94a699>:0
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in <d6223712465241819a0ed6175a4340a0>:0
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <d6f2f21c0fef46fd8872c1b187de54f1>:0
  at Android.Support.Design.Widget.Snackbar.Make (Android.Views.View view, Java.Lang.ICharSequence text, System.Int32 duration) [0x00078] in <0d997552ddad494094d94e2a353b2022>:0
  at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass20_0.<ToastAppCompat>b__0 () [0x0002d] in C:\dev\acr\userdialogs\src\Acr.UserDialogs.Android\Fragments\AbstractDialogFragment.cs:101
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <d6f2f21c0fef46fd8872c1b187de54f1>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <d6f2f21c0fef46fd8872c1b187de54f1>:0
  at at (wrapper dynamic-method) System.Object:5f5ea637-664e-4e60-b933-280014418007 (intptr,intptr)
  at java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
  at at android.support.design.widget.Snackbar.setText(Snackbar.java:340)
  at at android.support.design.widget.Snackbar.make(Snackbar.java:216)
  at at mono.java.lang.RunnableImplementor.n_run(Native Method)
  at at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
  at at android.app.Activity.runOnUiThread(Activity.java:5543)
  at at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
  at at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
  at at android.view.View.performClick(View.java:5207)
  at at android.view.View$PerformClick.run(View.java:21168)
  at at android.os.Handler.handleCallback(Handler.java:746)
  at at android.os.Handler.dispatchMessage(Handler.java:95)
  at at android.os.Looper.loop(Looper.java:148)
  at at android.app.ActivityThread.main(ActivityThread.java:5491)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```

**Comment by aritchie** [comment]
This has been answered several times already.  Uninstall all packages of Acr.UserDialogs and reinstall OR make sure you do a full clean build.

**Comment by Teja-developer** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sudhaseshu.gitamfeed/com.example.sudhaseshu.gitamfeed.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2911)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
        at com.example.sudhaseshu.gitamfeed.MainActivity.onCreate(MainActivity.java:85)
        at android.app.Activity.performCreate(Activity.java:7041)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
09-15 11:17:50.325 599-599/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=27773 uid=10414 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
09-15 11:17:50.326 599-599/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=27773 uid=10414 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
09-15 11:17:52.105 1152-6277/? E/JobSchedulerService: jobid:20536
    java.lang.IllegalStateException: Same jobid in systemuid.
        at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:710)
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:1999)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
        at com.android.server.backup.FullBackupJob.schedule(FullBackupJob.java:52)
        at com.android.server.backup.BackupManagerService$4.run(BackupManagerService.java:5389)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
09-15 11:17:52.150 810-856/? E/ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
     return value 2
09-15 11:17:54.223 1152-1344/? E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
    no controller energy info supplied for bluetooth
09-15 11:18:10.759 798-1236/? E/qti_sensors_hal: processInd: pickup data: state: 0.000000 flag: 2.000000 SAM TS: 1802438527 HAL TS:186074123585750 elapsedRealtimeNano:186074179590834
09-15 11:18:10.810 798-1187/? E/qti_sensors_hal: processInd: DeviceOrientation: Orientation: 1.000000 wakeup: 0 SAM TS: 1802439483 HAL TS:186074152760555elapsedRealtimeNano:186074230160157
09-15 11:18:30.219 1299-1577/? E/QC-QMI: acquire netmgr_wl for netmgr_qmi_wds_ind_cb: received indication=0x1 on link=2
09-15 11:18:30.231 3827-3827/? E/QImsService: ImsServiceSub : handleSrvStatusUpdate tracker is null so not updating global VT capability
09-15 11:18:30.231 3827-3827/? E/ImsMultiEndpointImpl: handleRefreshViceInfo listener null
09-15 11:18:32.805 14088-27586/? E/NetworkScheduler.TED: Unable to bind to task service: ComponentInfo{com.jabong.android/com.firebase.jobdispatcher.GooglePlayReceiver}
09-15 11:18:32.823 14088-27473/? E/NetworkScheduler: Unknown result code received: 4
09-15 11:20:47.774 14450-14562/? E/memtrack: Couldn't load memtrack module
 Please solve my problem
