### ISSUE TITLE
Toasts with Xamarin.Forms Android AppCompat throws android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true

### ISSUE THREAD

**Issue by adriancho5692** [aritchie/userdialogs#339]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [x] PCL

## Version of OS(s) listed above with issue
Android 4.4.4

UserDialogs.Instance.Toast() throws exception when using Xamarin.Forms AppCompat Activity in Android.

I need to use AppCompat for project purpose. Alerts and Loadings work well, the problem is just with Toasts.

Curiously, Acr.UserDialogs toasts work well if I also include [https://github.com/EgorBo/Toasts.Forms.Plugin](url) Nuget in my project with no code modifications. Just including it.

I would like a way (if possible) to make toasts work with AppCompat without including the previous Nuget.

## Version of ACR UserDialogs Library
6.3.8

## Expected Behaviour
Show toast normally in Xamarin.Forms Android AppCompat

## Actual Behavior
android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
	at android.view.LayoutInflater.inflate(LayoutInflater.java:459)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.support.design.widget.Snackbar.<init>(Snackbar.java:188)
	at android.support.design.widget.Snackbar.make(Snackbar.java:215)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.app.Activity.runOnUiThread(Activity.java:5042)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5679)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
Xamarin caused by: Android.Views.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/548405a1/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in /Users/builder/data/lanes/4009/c9880f98/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:12649 
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00000] in /Users/builder/data/lanes/4009/c9880f98/source/monodroid/src/Mono.Android/JNIEnv.g.cs:562 
  at Android.Support.Design.Widget.Snackbar.Make (Android.Views.View view, Java.Lang.ICharSequence text, System.Int32 duration) [0x00078] in <12ef52c9fdb344f58cbdf75db3fa86d8>:0 
  at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass20_0.<ToastAppCompat>b__0 () [0x00020] in C:\dev\acr\userdialogs\src\Acr.UserDialogs.Android\UserDialogsImpl.cs:177 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/4009/c9880f98/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/4009/c9880f98/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Java.Lang.IRunnable.cs:81 
  at (wrapper dynamic-method) System.Object:548fd632-5ca2-4069-aae0-4940e9508e24 (intptr,intptr)
  --- End of managed Android.Views.InflateException stack trace ---
android.view.InflateException: <merge /> can be used only with a valid ViewGroup root and attachToRoot=true
	at android.view.LayoutInflater.inflate(LayoutInflater.java:459)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.support.design.widget.Snackbar.<init>(Snackbar.java:188)
	at android.support.design.widget.Snackbar.make(Snackbar.java:215)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.app.Activity.runOnUiThread(Activity.java:5042)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5679)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by aritchie** [comment]
This usually happens when the android support packages are out of whack.  Best suggestion is to uninstall all ACR libs and reinstall.

**Comment by aritchie** [comment]
Haven't heard back.  Please reopen with additional findings if you still have an issue

**Comment by adriancho5692** [comment]
Sorry, I was not able to asnwer before. Yes, reinstalling the Nuget resolved the problem. Now works perfectly. Thanks!
