### ISSUE TITLE
Windows App Store support

### ISSUE THREAD

**Issue by astrazzari72** [aritchie/userdialogs#35]
Is Windows App Store support planned to do?
I tried to reference Acr.UserDialogs in a Win 8.1 Store App and init it calling

UserDialogs.Init();

in the MainPage ctor link in WinPhone, but I obtain the following exception:

System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=You must call the Init() method from the platform project, not this PCL version
  Source=Acr.UserDialogs
  StackTrace:
       at Acr.UserDialogs.UserDialogs.Init()
       at AW.PaintAnatomy.Win.MainPage..ctor()
       at AW.PaintAnatomy.Win.AW_PaintAnatomy_Win_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage()
       at AW.PaintAnatomy.Win.AW_PaintAnatomy_Win_XamlTypeInfo.XamlUserType.ActivateInstance()
  InnerException: 

Thanks

**Comment by aritchie** [comment]
https://github.com/aritchie/userdialogs/issues/19
