### ISSUE TITLE
Not able to create Android Release Build

### ISSUE THREAD

**Issue by kartiksolanki** [aritchie/userdialogs#397]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] Android

## Version of ACR UserDialogs Library
6.3.10

## Expected Behaviour
Should create android release build in Linking behaviour to SDK Assemblies only.

## Actual Behavior
Throwing error as below:

The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Graphics.Drawables.Drawable Splat.BitmapMixins::ToNative(Splat.IBitmap)' (defined in assembly 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Graphics.Drawables.Drawable Splat.BitmapMixins::ToNative(Splat.IBitmap)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Run(Pipeline pipeline, LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Any idea how to get over it ? One solution in setting Linking behaviour to NONE but that increases the size of my app and is not a valid solution.

**Comment by kartiksolanki** [comment]
Found out that the reference to SPLAT package was not there in my android project. So I have resolved this issues by manually adding SPLAT package reference in my android package.
