### ISSUE TITLE
Failed to resolve Android.Support.Design.Widget.BottomSheetDialog

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [aritchie/userdialogs#416]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] Android
 - [] NET Standard 1.4

## Version of OS(s) listed above with issue
7.1

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
The Application should build in release mode.

## Actual Behavior

The application is not compiling and throwing the below build error when compiled in release mode.
It's working when compiled in debug mode.

_If applicable, please include entire exception - type, message, stacktrace_

The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'Android.App.Dialog Acr.UserDialogs.Fragments.BottomSheetDialogFragment::CreateDialog(Acr.UserDialogs.ActionSheetConfig)' in assembly: 'Acr.UserDialogs.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Support.Design.Widget.BottomSheetDialog
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

These are the android SDK installed on my machine

![image](https://user-images.githubusercontent.com/10863510/29460751-bbbe7fd4-8446-11e7-9f6d-74215fa00ba8.png)

**Comment by sawankumarbundelkhandi** [comment]
The issue is already addressed in https://github.com/aritchie/userdialogs/issues/413. It's working after downgrading the support libs.

Closing the issue.

Thanks for the plugin.
