### ISSUE TITLE
ActionSheetAsync - OnCancelListener OnDismissListener crash

### ISSUE THREAD

**Issue by KennethKr** [aritchie/userdialogs#424]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue

Android 7.1.1

## Version of ACR UserDialogs Library

6.5.1

## Expected Behaviour

ActionSheetAsync shown.

## Actual Behavior

I'm using a FragmentActivity and ActionSheetAsync. When I await the ActionSheetAsync method, it crashes with the following exception: 

Java.Lang.IllegalStateException: You can not set Dialog's OnCancelListener or OnDismissListener
  at java.lang.IllegalStateException: You can not set Dialog's OnCancelListener or OnDismissListener
  at at android.app.DialogFragment.onActivityCreated(DialogFragment.java:486)
  at at android.app.Fragment.performActivityCreated(Fragment.java:2362)
  at at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
  at at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
  at at android.app.BackStackRecord.run(BackStackRecord.java:816)
  at at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
  at at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
  at at android.os.Handler.handleCallback(Handler.java:751)
  at at android.os.Handler.dispatchMessage(Handler.java:95)
  at at android.os.Looper.loop(Looper.java:154)
  at at android.app.ActivityThread.main(ActivityThread.java:6119)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by aritchie** [comment]
Most of the newer android design support libraries require the appcompatactivity to render.  I have test cases setup for Activity (old school) and AppCompatActivity (newer way), but not the middle man FragmentActivity

**Comment by KennethKr** [comment]
Ok. I'm just gonna change to AppCompatActivity. As for UserDialogs, it seems it is supported when you browse the code, like I did. It should either be removed or fixed?

`        public override IDisposable ActionSheet(ActionSheetConfig config)
        {
            var activity = this.TopActivityFunc();
            if (activity is AppCompatActivity)
            {
                if (config.UseBottomSheet)
                    return this.ShowDialog<Fragments.BottomSheetDialogFragment, ActionSheetConfig>((AppCompatActivity)activity, config);

                return this.ShowDialog<ActionSheetAppCompatDialogFragment, ActionSheetConfig>((AppCompatActivity)activity, config);
            }

            if (activity is FragmentActivity)
                return this.ShowDialog<ActionSheetDialogFragment, ActionSheetConfig>((FragmentActivity)activity, config);

            return this.Show(activity, () => new ActionSheetBuilder().Build(activity, config));
        }`

**Comment by aritchie** [comment]
The chunk of offending code was removed with v7
