### ISSUE TITLE
 java.lang.RuntimeException: Translation has been interrupted

### ISSUE THREAD

**Issue by sergio11** [aritchie/userdialogs#430]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Android 7.0, 6.0.1

## Version of ACR UserDialogs Library
6.4.1

## Initial project configuration before package installation

```
<packages>
  <package id="Ansuria.XFGloss" version="1.0.6.59" targetFramework="monoandroid71" />
  <package id="Com.Airbnb.Android.Lottie" version="1.0.0.7" targetFramework="monoandroid71" />
  <package id="Com.Airbnb.Xamarin.Forms.Lottie" version="1.0.0.7" targetFramework="monoandroid71" />
  <package id="MvvmCross" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.Binding" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.Core" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.Forms" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.Platform" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.StarterPack" version="5.2.1" targetFramework="monoandroid71" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="monoandroid71" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="monoandroid71" />
  <package id="PInvoke.BCrypt" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.Kernel32" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.NCrypt" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.Windows.Core" version="0.3.2" targetFramework="monoandroid71" />
  <package id="Plugin.CurrentActivity" version="1.0.1" targetFramework="monoandroid71" />
  <package id="Refractored.XamForms.PullToRefresh" version="1.1.0" targetFramework="monoandroid71" />
  <package id="Rg.Plugins.Popup" version="1.0.4" targetFramework="monoandroid71" />
  <package id="UXDivers.Artina.Shared" version="2.0.60" targetFramework="monoandroid71" />
  <package id="UXDivers.Artina.Shared.Base" version="2.0.60" targetFramework="monoandroid71" />
  <package id="UXDivers.Effects" version="0.6.0" targetFramework="monoandroid71" />
  <package id="Validation" version="2.2.8" targetFramework="monoandroid71" />
  <package id="Xam.Plugin.DeviceInfo" version="3.0.1" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Forms.ImageCircle" version="1.8.1" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Settings" version="3.0.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Auth" version="1.5.0.3" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading" version="2.2.19" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.19" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.19" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.247" targetFramework="monoandroid71" />
</packages>
```
## Update needed to install the package

![user_dialogs](https://user-images.githubusercontent.com/6996211/31049361-bc2f9086-a631-11e7-9d63-dd65d6b7c160.PNG)

## Version of packages after installation

```
<packages>
  <package id="Acr.Support" version="2.1.0" targetFramework="monoandroid71" />
  <package id="Acr.UserDialogs" version="6.4.1" targetFramework="monoandroid71" />
  <package id="AndHUD" version="1.2.0" targetFramework="monoandroid71" />
  <package id="Ansuria.XFGloss" version="1.0.6.59" targetFramework="monoandroid71" />
  <package id="Com.Airbnb.Android.Lottie" version="1.0.0.7" targetFramework="monoandroid71" />
  <package id="Com.Airbnb.Xamarin.Forms.Lottie" version="1.0.0.7" targetFramework="monoandroid71" />
  <package id="MvvmCross" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.Binding" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.Core" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.Forms" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.Platform" version="5.2.1" targetFramework="monoandroid71" />
  <package id="MvvmCross.StarterPack" version="5.2.1" targetFramework="monoandroid71" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="monoandroid71" />
  <package id="PCLCrypto" version="2.0.147" targetFramework="monoandroid71" />
  <package id="PInvoke.BCrypt" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.Kernel32" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.NCrypt" version="0.3.2" targetFramework="monoandroid71" />
  <package id="PInvoke.Windows.Core" version="0.3.2" targetFramework="monoandroid71" />
  <package id="Plugin.CurrentActivity" version="1.0.1" targetFramework="monoandroid71" />
  <package id="Refractored.XamForms.PullToRefresh" version="1.1.0" targetFramework="monoandroid71" />
  <package id="Rg.Plugins.Popup" version="1.0.4" targetFramework="monoandroid71" />
  <package id="Splat" version="1.6.2" targetFramework="monoandroid71" />
  <package id="UXDivers.Artina.Shared" version="2.0.60" targetFramework="monoandroid71" />
  <package id="UXDivers.Artina.Shared.Base" version="2.0.60" targetFramework="monoandroid71" />
  <package id="UXDivers.Effects" version="0.6.0" targetFramework="monoandroid71" />
  <package id="Validation" version="2.2.8" targetFramework="monoandroid71" />
  <package id="Xam.Plugin.DeviceInfo" version="3.0.1" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Forms.ImageCircle" version="1.8.1" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Settings" version="3.0.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Annotations" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.UI" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Core.Utils" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.CustomTabs" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Design" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Fragment" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Media.Compat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Transition" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.CardView" version="23.3.0" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.Palette" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="25.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Auth" version="1.5.0.3" targetFramework="monoandroid71" />
  <package id="Xamarin.Build.Download" version="0.4.3" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading" version="2.2.19" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.19" targetFramework="monoandroid71" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.19" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.4.247" targetFramework="monoandroid71" />
</packages>
```
## Actual Behavior

When compiling the project, I get a lot of warnings like:
```
Skipping Bulltect.Droid.Resource.Attribute.mediaRouteChooserPrimaryTextStyle. Please check that your Nuget Package versions are compatible.	Bulltect.Droid
Skipping Bulltect.Droid.Resource.Attribute.mediaRouteChooserSecondaryTextStyle. Please check that your Nuget Package versions are compatible.	Bulltect.Droid
Skipping Bulltect.Droid.Resource.Attribute.mediaRouteChooserSecondaryTextStyle. Please check that your Nuget Package versions are compatible.	Bulltect.Droid
Skipping Bulltect.Droid.Resource.Attribute.mediaRouteChooserSecondaryTextStyle. Please check that your Nuget Package versions are compatible.	Bulltect.Droid		
```	

Compilation ends with the following error:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
1>  java.lang.RuntimeException: Translation has been interrupted
1>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
1>  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
1>  	at com.android.dx.command.dexer.Main.run(Main.java:277)
1>  	at com.android.dx.command.dexer.Main.main(Main.java:245)
1>  	at com.android.dx.command.Main.main(Main.java:106)
1>  Caused by: java.lang.InterruptedException: Too many errors
1>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
1>  	... 4 more
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1973,3): error : java.lang.IllegalArgumentException: already added :  Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
```
			
## Desired Behavior

What is the most stable version I can use for my initial setup? I have tried to go down to version 6.0.1 without much success. Thank you very much in advance.

**Comment by aritchie** [comment]
I don't see anything that suggests a problem with this library.  My guess is there is conflicts going on with the android support libraries.  Just use the latest Acr.UserDialogs 6.5.1 with the latest stable android support libraries
