### ISSUE TITLE
Error inflating class android.support.design.widget.Snackbar$SnackbarLayout

### ISSUE THREAD

**Issue by AgusQuiroga** [aritchie/userdialogs#431]
On Android.

## Version of OS(s) listed above with issue
Minimum Android Version 4.1 (API 16)
Taget Android Version 7.1 (API 25)

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Show a Toast Message.

```
var toastConfig = new ToastConfig("Toasting...");
toastConfig.SetDuration(3000);
toastConfig.SetBackgroundColor(System.Drawing.Color.FromArgb(12, 131, 193));

UserDialogs.Instance.Toast(toastConfig);
```

## Actual Behavior
App crashes with exception:

> Error inflating class android.support.design.widget.Snackbar$SnackbarLayout

Using a custom theme extending Theme.AppCompat.Light.DarkActionBar

**Comment by aritchie** [comment]
Please include the full stack trace

**Comment by AgusQuiroga** [comment]
Sorry, forgot the trace.

```
Package: com.webq.fram.catalog_app
Version Code: 3
Version Name: 1.3
Android: 5.1
Android Build: vbox86p-userdebug 5.1 LMY47D eng.Xamarin.20151013.103248 test-keys
Manufacturer: Xamarin
Model: Nexus 5 (Lollipop)
Thread: main-1
CrashReporter Key: E406B0F9-CC8B-F4CB-BA94-EAEC775162195AB0DF68
Start Date: Mon Oct 02 18:08:58 GMT-03:00 2017
Date: Mon Oct 02 18:11:04 GMT-03:00 2017
Format: Xamarin

android.view.InflateException: Binary XML file line #15: Error inflating class android.support.design.widget.Snackbar$SnackbarLayout
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.support.design.widget.BaseTransientBottomBar.<init>(BaseTransientBottomBar.java:244)
	at android.support.design.widget.Snackbar.<init>(Snackbar.java:112)
	at android.support.design.widget.Snackbar.make(Snackbar.java:145)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.app.Activity.runOnUiThread(Activity.java:5293)
	at md5270abb39e60627f0f200893b490a1ade.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
	at md5270abb39e60627f0f200893b490a1ade.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:30)
	at android.view.View.performClick(View.java:4780)
	at android.view.View$PerformClick.run(View.java:19866)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.Snackbar$SnackbarLayout" on path: DexPathList[[zip file "/data/app/com.webq.fram.catalog_app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.webq.fram.catalog_app-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.view.LayoutInflater.createView(LayoutInflater.java:571)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	... 20 more
	Suppressed: java.lang.ClassNotFoundException: android.support.design.widget.Snackbar$SnackbarLayout
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 23 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
Xamarin caused by: Java.Lang.RuntimeException: Binary XML file line #15: Error inflating class android.support.design.widget.Snackbar$SnackbarLayout ---> Java.Lang.ClassNotFoundException: Didn't find class "android.support.design.widget.Snackbar$SnackbarLayout" on path: DexPathList[[zip file "/data/app/com.webq.fram.catalog_app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.webq.fram.catalog_app-1/lib/x86, /vendor/lib, /system/lib]]
   --- End of inner exception stack trace ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <52d366583c894658a7ebfcff09fe6104>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <a6d795ed387943d489da456e6e9427a0>:0 
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <584ccd61b4834d4e9e98de804616f35f>:0 
  at Android.Support.Design.Widget.Snackbar.Make (Android.Views.View view, Java.Lang.ICharSequence text, System.Int32 duration) [0x00077] in <166317b07ca041a09eb746c23b463deb>:0 
  at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass20_0.<ToastAppCompat>b__0 () [0x00048] in <7cbdc3c8df744ea4aa132dbc1f757ca0>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <584ccd61b4834d4e9e98de804616f35f>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <584ccd61b4834d4e9e98de804616f35f>:0 
  at (wrapper dynamic-method) System.Object:4ce1a897-0438-40c1-a6e1-5725bd020af1 (intptr,intptr)
  --- End of managed Java.Lang.RuntimeException stack trace ---
android.view.InflateException: Binary XML file line #15: Error inflating class android.support.design.widget.Snackbar$SnackbarLayout
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.support.design.widget.BaseTransientBottomBar.<init>(BaseTransientBottomBar.java:244)
	at android.support.design.widget.Snackbar.<init>(Snackbar.java:112)
	at android.support.design.widget.Snackbar.make(Snackbar.java:145)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.app.Activity.runOnUiThread(Activity.java:5293)
	at md5270abb39e60627f0f200893b490a1ade.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
	at md5270abb39e60627f0f200893b490a1ade.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:30)
	at android.view.View.performClick(View.java:4780)
	at android.view.View$PerformClick.run(View.java:19866)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.Snackbar$SnackbarLayout" on path: DexPathList[[zip file "/data/app/com.webq.fram.catalog_app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.webq.fram.catalog_app-1/lib/x86, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.view.LayoutInflater.createView(LayoutInflater.java:571)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	... 20 more
	Suppressed: java.lang.ClassNotFoundException: android.support.design.widget.Snackbar$SnackbarLayout
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 23 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by aritchie** [comment]
This problem usually happens with older android support libraries. Make sure to use 25.0.2.  Occasionally the compiler screws up and doesn’t pull in the resources properly.  Clean the bin/obj folders and try again.

**Comment by AgusQuiroga** [comment]
Thx, Issue solved.

**Comment by VahidShir** [comment]
For me the crash log was `Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.AlertDialogLayout"`

So I needed to add `-keep class android.support.v7.widget.** {*; }`
