### ISSUE TITLE
Gett BadToken Exception

### ISSUE THREAD

**Issue by vbisbest** [aritchie/userdialogs#44]
This is in an Android only Xamarin app (not Xamarin.Forms).  When I instantiate my main activity I call:
UserDialogs.Init(() => this);

However on all other Activities, the dialogs fail to appear.  No error, just nothing happens unless I call:
UserDialogs.Init(() => this); 
Now the dialog pops ups. However when I go back to a previous Activity and open a dialog , I get this error:

System.Diagnostics.Debugger.Mono_UnhandledException (ex={Android.Views.WindowManagerBadTokenException: Exception of type 'Android.Views.WindowManagerBadTokenException' was thrown.
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/1978/f98871a9/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
at Android.Runtime.JNIEnv.CallObjectMethod (intptr,intptr) [0x00063] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:178
at Android.App.AlertDialog/Builder.Show () [0x00043] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Android.App.AlertDialog.cs:1626
at Acr.UserDialogs.UserDialogsImpl/<>c__DisplayClass3_0.<ActionSheet>b__4 () <IL 0x00006, 0x00027>
at Acr.UserDialogs.Utils.RequestMainThread (System.Action) <IL 0x0001f, 0x000b8>
at Acr.UserDialogs.UserDialogsImpl.ActionSheet (Acr.UserDialogs.ActionSheetConfig) <IL 0x000fd, 0x00563>
at MineFriendsAndroid.FriendsActivity.HandleItemClick (object,Android.Widget.AdapterView/ItemClickEventArgs) [0x0007d] in /Users/ray/Projects/MineFriendsAndroid/MineFriendsAndroid/FriendsActivity.cs:347
at Android.Widget.AdapterView/IOnItemClickListenerImplementor.OnItemClick (Android.Widget.AdapterView,Android.Views.View,int,long) [0x0000d] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Android.Widget.AdapterView.cs:283
at Android.Widget.AdapterView/IOnItemClickListenerInvoker.n_OnItemClick_Landroid_widget_AdapterView_Landroid_view_View_IJ (intptr,intptr,intptr,intptr,int,long) [0x00019] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Android.Widget.AdapterView.cs:211
at (wrapper dynamic-method) object.b3b181d3-f6ab-4e54-a135-e4981019443b (intptr,intptr,intptr,intptr,int,long) <IL 0x00029, 0x0005b>

  --- End of managed exception stack trace ---
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@20c1c1b1 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:562)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:282)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:298)
	at android.app.AlertDialog$Builder.show(AlertDialog.java:993)
	at mono.android.widget.AdapterView_OnItemClickListenerImplementor.n_onItemClick(Native Method)
	at mono.android.widget.AdapterView_OnItemClickListenerImplementor.onItemClick(AdapterView_OnItemClickListenerImplementor.java:29)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
	at android.widget.AbsListView$3.run(AbsListView.java:3860)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5257)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
}) in /Users/builder/data/lanes/1978/f98871a9/source/mono/mcs/class/corlib/System.Diagnostics/Debugger.cs:122

Thanks.

**Comment by aritchie** [comment]
This is not a bug.  UserDialogs.Init takes a factory function specifically for receiving the top activity from some third party mechanism.  If you take a look at the readme, you'll see how I do it for both xamarin forms & mvvmcross.

**Comment by aritchie** [comment]
I just read your bug that you are doing this for an android app only.  Not sure why you would use this library for one platform only, but in any case, you'll need to record the top activity yourself OR reset the factory method every time OnResume is called within each activity

**Comment by fedotovsi** [comment]
Hi, aritchie! Sorry about that, I didn't find a place where I can ask my question.
From readme isn't clear how to initialize UserDialogs for Android App. If I correctly understood I should do it once  in every activity in OnCreate method for ex. am I right? Is a difference between if I will do it before calling base.OnCreate or not? e.g. in my activity:

protected override void OnCreate(Bundle bundle)
        {
            UserDialogs.Init(this);
            base.OnCreate(bundle);
        }
This important for me, I did it in this way because of VM, if it should be after base method I need to rethink my vm(((  I just want to be sure if what I did is it correct?
 Thanks in advice.

**Comment by aritchie** [comment]
You only have to call UserDialogs.Init(this) from your main launcher

**Comment by fedotovsi** [comment]
yes, it works until, during showing progress user change orientation of the screen, unfortunately,
it throws a exception: "View=com.android.internal.policy.impl.PhoneWindow$DecorView{101ff78 G.E..... R.....ID 0,0-125,133} not attached to window manager"
Anyway, thanks for you help, I get the point, I will try to find out why it happens.

**Comment by aritchie** [comment]
It's because you are likely reinitializing over and over again.  The factory method is where you supply the top activity (using mvvmcro as or something similar) or passing only the initial activity from the main launcher.  On the second method, it uses that activity to attach a lifecycle monitor to all activities.  

That error means you are supplying the top activity yourself somehow which is often wrong.

**Comment by fedotovsi** [comment]
No, unfortunately, if I make reinit in each activity, progress bar  simple disappears on rotation without crashing, it crashes only if make UserDialogs.Init() once in main launcher regardless with factory or no. Maybe I something didn't understand...
so I put UserDialogs.Init(() => Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity);
in my main launcher no other places only in main launcher, and it crashes with those exception.

**Comment by aritchie** [comment]
The progress bar does not survive rotation currently.  As for whatever your issue is, you should only call Init from your main launcher as shown in the sample.  I can only guess at this point what may be wrong
