### ISSUE TITLE
User dialog confirmasync crashes when it is dismissed while app is in background

### ISSUE THREAD

**Issue by rspl-nilesh** [aritchie/userdialogs#506]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0
## Version of OS(s) listed above with issue 
Android version - 4.4.2
Xamarin.Android.Support.v4 - 25.4.0.2

## Version of ACR UserDialogs Library
6.5.1

## Steps to reproduce
1) Just show dialog with below mentioned code
await UserDialogs.Instance.ConfirmAsync(message, title, Resources.YesText, Resources.NoText, cancellationToken);
2) Put app in background and perform cancellationToken.Cancel after sometime ensure app should be in background when cancellationToken.Cancel is fired.

## Expected Behaviour
Should not crash. Instead, if needed dialog be canceled when an app comes in the foreground.

## Actual Behavior
App crashes

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1884)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1902)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
	at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:205)
	at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:171)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5883)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
	at dalvik.system.NativeStart.main(Native Method)

Happy to provide more information if required.

**Comment by aritchie** [comment]
Please know that this library is not a window/viewstate manager.  It is your responsibility to be aware of the state of the view before calling for anything as it would be doing this in raw native code.  

I have made some updates in v7 that help alleviate this, but it doesn't change the practice.  Also note, I won't call cancel automatically because it is optional and not necessarily what needs to happen when a dismissal operation is going to occur.
