### ISSUE TITLE
Update from 6.5 to 7.0 causes exceptions

### ISSUE THREAD

**Issue by Sebastian1989101** [aritchie/userdialogs#507]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [x] NET Standard 2.0

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Should work

## Actual Behavior
After updating Acr.UserDialogs to the latest version, I always get this exception when I try to build Android: 

```
The "GenerateJavaStubs" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'Acr.UserDialogs.Interface, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Acr.UserDialogs.Interface.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Java.Interop.Tools.Cecil.TypeDefinitionRocks.<GetTypeAndBaseTypes>d__1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Java.Interop.Tools.Cecil.TypeDefinitionRocks.IsSubclassOf(TypeDefinition type, String typeName)
   at Java.Interop.Tools.JavaCallableWrappers.JavaTypeScanner.AddJavaTypes(List`1 javaTypes, TypeDefinition type)
   at Java.Interop.Tools.JavaCallableWrappers.JavaTypeScanner.GetJavaTypes(IEnumerable`1 assemblies, IAssemblyResolver resolver)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MHWorldCompanion.Droid		
```	

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
v7 only has 1 dll, prior to that, there were 2 - Acr.UserDialogs.dll and Acr.UserDialogs.Interface.dll.  It isn't anything wrong with the nuget package itself.  It is something wrong with nuget or android keeping the old artifact that should have been uninstalled.  Just find all traces of Acr.UserDialogs.Interface and remove it.  You may need to clear bin/obj

**Comment by Sebastian1989101** [comment]
Seems like a manual deletion of the obj folder was the solution... strange normally that is exactly what a rebuilt should do... thanks for the quick reply & help!
