### ISSUE TITLE
AlertAsync task never finishes if being called in background

### ISSUE THREAD

**Issue by arctouch-sergeymetlov** [aritchie/userdialogs#532]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [+] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Sample app (Samples.Droid)

## Version of ACR UserDialogs Library
The current master codebase.

## Actual Behavior

The task received by `AlertAsync` call never finishes if being called when the app is in background.

To reproduce the issue place the following code in the sample app (`StandardViewModel.cs`):

```
                new CommandViewModel
                {
                    Text = "Alert",
                    Command = this.Create(async token =>
                    {
                        await Task.Delay(3000);
                        await this.Dialogs.AlertAsync("Test alert", "Alert Title", null, token);
                    })
                },
```

After clicking the "Alert" button in the app, move to the background by clicking the system Android's Home button.
When `AlertAsync` is being called out, it fails with the following exception and the task never finishes execution.

```
[Error][] Java.Lang.IllegalStateException: Can not perform this action after onSaveInstanceState
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <3cb12bce834a498199b2be6cd3e00922>:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00015] in <4e64e43c99f8466aaffc15cc372a3c04>:0 
  at Android.Support.V4.App.DialogFragment.Show (Android.Support.V4.App.FragmentManager manager, System.String tag) [0x000a3] in <1e89c43d3c7d48b5ba69bfc0b1bdf114>:0 
  at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass23_0`2[TFragment,TConfig].<ShowDialog>b__0 () [0x00018] in /Users/sm/dev/userdialogs/src/Acr.UserDialogs/Platforms/Android/UserDialogsImpl.cs:282 
  at Acr.UserDialogs.Extensions+<>c__DisplayClass2_0.<SafeRunOnUi>b__0 () [0x00002] in /Users/sm/dev/userdialogs/src/Acr.UserDialogs/Platforms/Android/Extensions.cs:52 
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1884)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1902)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.app.Activity.runOnUiThread(Activity.java:5511)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
It’s not supposed to.  That’s why I give a spot cancellation tokens

**Comment by arctouch-sergeymetlov** [comment]
So what's your recommendation on this @aritchie ?

**Comment by aritchie** [comment]
Use a cancellation token!!  Cancel it when the view/app goes to the background

**Comment by arctouch-sergeymetlov** [comment]
It's obvious the task should be completed no matter if there was an internal exception.
