### ISSUE TITLE
XamlParseException (Xamarin Forms, Win8.1)

### ISSUE THREAD

**Issue by Riwen** [aritchie/userdialogs#58]
I'm getting this exception when trying to call the "Loading()" method.

Stack trace:
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Acr.UserDialogs.ProgressContentDialog.InitializeComponent()
   at Acr.UserDialogs.ProgressDialog..ctor()
   at Acr.UserDialogs.UserDialogsImpl.CreateDialogInstance()
   at Acr.UserDialogs.AbstractUserDialogs.Progress(ProgressDialogConfig config)
   at Acr.UserDialogs.AbstractUserDialogs.Loading(String title, Action onCancel, String cancelText, Boolean show, Nullable`1 maskType)
   at FoodOrder.RegistraionPage.<>c.<.ctor>b__0_0(Object sender, EventArgs e)
   at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked()
   at Xamarin.Forms.Platform.WinRT.ButtonRenderer.OnButtonClick(Object sender, RoutedEventArgs e)

**Comment by aritchie** [comment]
There is almost no point using it yet windows.  It is more in an alpha mode

**Comment by Riwen** [comment]
Ah, I see. Great work, though.

**Comment by aritchie** [comment]
Thanks.

Just as a though, I'm not sure if the UWP package runs on windows 8??  In this case, loading definitely shouldn't be considered stable, but I was able to get it running.

**Comment by aritchie** [comment]
This was a defect with the nuspec.  UWP and WP8 are supported, not win8
