### ISSUE TITLE
Compatibility issue with AndHud v1.4.1

### ISSUE THREAD

**Issue by danielPollackGitHub** [aritchie/userdialogs#583]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Xamarin.Android.Support.V4, Xamarin v28.0.0.1
Xamarin.Android.Support.v7.AppCompat v28.0.0.1
Xamarin.Android.Support.v7.CardView v28.0.0.1
Xamarin.Android.Support.v7.MediaRouter v28.0.0.1

## Version of ACR UserDialogs Library
Acr.Mvvmcross.plugins.userDialogs v5.0.0
Acr.Support v2.1.0
Acr.UserDialogs v7.0.1

## Expected Behaviour
Build in release with no errors

## Actual Behavior
Severity Code Description Project File Line Suppression State
Error The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Acr.UserDialogs.ProgressDialog/<>c__DisplayClass18_0::b__0()' in assembly: 'Acr.UserDialogs.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void AndroidHUD.AndHUD::Show(Android.Content.Context,System.String,System.Int32,AndroidHUD.MaskType,System.Nullable`1<System.TimeSpan>,System.Action,System.Boolean,System.Action)
at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
at Mono.Linker.Steps.MarkStep.ProcessQueue()
--- End of inner exception stack trace ---
at Mono.Linker.Steps.MarkStep.ProcessQueue()
at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
at Mono.Linker.Steps.MarkStep.Process()
at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
at Mono.Linker.Pipeline.Process(LinkContext context)
at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
at Xamarin.Android.Tasks.LinkAssemblies.Execute()
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() Toolbox.Forms.Droid

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Listen - you just complained on another issue displaying frustration on an OSS project which is for free.  Now you opening a duplicate issue.  Please be respectful!

**Comment by danielPollackGitHub** [comment]
My apologies.
