### ISSUE TITLE
Error Xamarin Forms (Android)

### ISSUE THREAD

**Issue by Jason55555** [aritchie/userdialogs#95]
it shows me this when i run it on Xamarin Android player and then my app goes black and doesnt show me anything! how can i fix it?

Java.Lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at --- End of managed exception stack trace ---
  at java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
  at Caused by: java.lang.reflect.InvocationTargetException
  at at java.lang.reflect.Method.invoke(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:372)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at ... 1 more
  at Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.TypeLoadException: Could not load type 'hello.MainActivity, hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
  at at (wrapper managed-to-native) System.Type.internal_from_name (string,bool,bool) <IL 0x0001c, 0x0006f>
  at System.Type.GetType (string,bool) [0x00011] in /Users/builder/data/lanes/2185/53fce373/source/mono/mcs/class/corlib/System/Type.cs:581
  at Java.Interop.TypeManager.n_Activate (intptr,intptr,intptr,intptr,intptr,intptr) [0x00062] in /Users/builder/data/lanes/2185/53fce373/source/monodroid/src/Mono.Android/src/Java.Interop/TypeManager.cs:144
  at at (wrapper dynamic-method) object.40f1f654-4631-47af-8f9f-c05d7702f641 (intptr,intptr,intptr,intptr,intptr,intptr) <IL 0x00029, 0x0004b>
  at at mono.android.TypeManager.n_activate(Native Method)
  at at mono.android.TypeManager.Activate(TypeManager.java:7)
  at at md573f45f3f60d2fb9be8043dc52245a8d7.MainActivity.<init>(MainActivity.java:22)
  at at java.lang.reflect.Constructor.newInstance(Native Method)
  at at java.lang.Class.newInstance(Class.java:1606)
  at at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
  at at android.app.ActivityThread.access$800(ActivityThread.java:151)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
  at at android.os.Handler.dispatchMessage(Handler.java:102)
  at at android.os.Looper.loop(Looper.java:135)
  at at android.app.ActivityThread.main(ActivityThread.java:5254)
  at ... 4 more

**Comment by aritchie** [comment]
I don't see one thing in this message that has anything to do with this library.

The source of your error is:
System.TypeLoadException: Could not load type 'hello.MainActivity, hello, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by Jason55555** [comment]
i am so sorry about that! 
i was just frustrated cause i cant seem to find a way to get it to work!

**Comment by aritchie** [comment]
Trying to get what to work?  The sample app with this library?
